name: Deploy Docusaurus Site

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the current repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ensure this matches your project requirements

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Ensure the script is executable
      - name: Make script executable
        run: chmod +x ./scripts/clone-and-copy.sh

      # Step 5: Run your script to clone the external repo and copy files
      - name: Clone external repo and copy files
        run: ./scripts/clone-and-copy.sh  # Ensure the script has execute permissions (chmod +x)

      # Step 6: Build the Docusaurus site
      - name: Build Docusaurus
        run: npm run build

      # Step 7: Install Netlify CLI
      - name: Install Netlify CLI
        run: npx netlify-cli

      # Step 8: Deploy to Netlify using the CLI
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npx netlify deploy --prod --dir=build --site=$NETLIFY_SITE_ID
